# note: 파드가 외부 서비스에 노출 할 수 있게 하는 객체
# note: 파드와 파드의 통신, 파드가 외부 인터넷과 통신을 위해서는 CNI플러그인과 Service가 필요함

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc # note: 서비스 이름
  labels: 
    app: nginx
spec:
  type: NodePort # note: 노드포트를 이용해서 서비스(service)를 외부에 노출시킴
  ports:
  - port: 8080
    nodePort: 31472
    targetPort: 80
  selector:
    app: nginx # note: 서비스(service)를 nginx레이블을 갖는 파드와 연결