apiVersion: v1
kind: Pod
metadata:
  name: hostpath
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: localpath 
          mountPath: /data/shared # note: nginx 라는 이름의 컨테이너에 /data/hostpath 디렉토리로 마운트
  volumes:
    - name: localpath
      hostPath:
        path: /tmp # note: 워커 노드의 /tmp 디렉토리를 hostPath로 이용
        type: Directory