apiVersion: v1
kind: Pod
metadata:
  name: emptydata # note: emptydata라는 파드 생성
spec:
  containers:
  - name: nginx # note: nginx라는 이름의 컨테이너를 생성해 /data/shared 디렉토리 마운트
    image: nginx
    volumeMounts:
    - name: shared-storage
      mountPath: /data/shared # note: data/shared 경로의 볼륨을 마운트
  volumes:
  - name: shared-storage
    emptyDir: {} # note: shared-storage라는 이름으로 emptyDir 기반의 볼륨을 생성
