# note: externalService란?
# note: external-service라는 이름으로 요청이 들어온다면 클러스터 외부에 존재하는 myservice.test.com이라는 주소를 반환하는것이 externalName 서비스임

# note: 외부FQDN: myservice.test.com
# note: CNAME: external-service

# note: FQDN이란? 도메인에 대한 전체 이름 표기 방식을 말합니다. ex) www.a.com 혹은 web01.a.com 같은 형태가 FQDN이다.
# note: CNAME이란? 하나의 도메인 이름을 다른 이름으로 매핑시키는 역할을 하는 DNS레코드의 일종이다.

kind: Service
apiVersion: v1
metadata:
  name: external-service
spec:
  type: ExternalName
  externalName: myservice.test.com # note: external-service와 연결하려는 외부 도메인 값을 설정
